---
default:
  image: fedora:34

  before_script:
    - dnf install -y ansible
    - ansible --version

  script:
    - cat /etc/ansible/ansible.cfg
    - printf '[defaults]\nroles_path=../' > /etc/ansible/ansible.cfg
    - pwd
    - ansible-playbook -vvv tests/test.yml -i tests/inventory --syntax-check
    - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
    - |
      ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)

#notifications:
  #webhooks: https://galaxy.ansible.com/api/v1/notifications/
