---
.pre:
  stage: setup
  image: fedora:34

  script:
    - dnf install -y ansible tar unzip
    - ansible --version

test:
  stage: test
  needs: [setup]
  script:
    - export ANSIBLE_ROLES_PATH=../
    - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
    - ansible-playbook -i tests/inventory tests/test.yml --connection=local 
    - |
      ansible-playbook -i tests/inventory tests/test.yml --connection=local \
      | grep -q 'changed=0.*failed=0'  \
      && (echo 'Idempotence test: pass' && exit 0) \
      || (echo 'Idempotence test: fail' && exit 1)


#deploy: 
  #notifications:
    #webhooks: https://galaxy.ansible.com/api/v1/notifications/
