---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: true

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --become-user root
  - &gt;
  ansible-playbook -i tests/inventory tests/test.yml --connection=local --become-user root
  | grep -q 'changed=0.*failed=0'
  &amp;&amp; (echo 'Idempotence test: pass' &amp;&amp; exit 0)
  || (echo 'Idempotence test: fail' &amp;&amp; exit 1)

#notifications:
  #webhooks: https://galaxy.ansible.com/api/v1/notifications/
