---
services: docker

# Use the new container infrastructure
sudo: true

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --become-user root
  - >-
    ansible-playbook -i tests/inventory tests/test.yml --connection=local --become-user root
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

#notifications:
  #webhooks: https://galaxy.ansible.com/api/v1/notifications/
